language: android

android:
  components:
    - build-tools-26.0.2
    - android-26
    - android-25
    - android-23
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - ./gradlew assemble

script:
    - ./gradlew check

jdk:
  - oraclejdk8
